/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Health */
        get: operations["get_source_health_v1_health_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cells */
        get: operations["list_cells_v1_cells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cells/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cell */
        get: operations["get_cell_v1_cells__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eta */
        get: operations["list_eta_v1_eta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/locations/{id}/eta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location Eta */
        get: operations["get_location_eta_v1_locations__id__eta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hazards/{layer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hazards */
        get: operations["list_hazards_v1_hazards__layer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles/{layer}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tile */
        get: operations["get_tile_v1_tiles__layer___z___x___y__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Alert */
        post: operations["approve_alert_v1_alerts__id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Alert */
        post: operations["cancel_alert_v1_alerts__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Verification */
        get: operations["list_verification_v1_verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replay/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Replay Events */
        get: operations["list_replay_events_v1_replay_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replay/{event_id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Control Replay */
        get: operations["control_replay_v1_replay__event_id__control_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thresholds */
        get: operations["list_thresholds_v1_thresholds_get"];
        put?: never;
        /** Set Threshold */
        post: operations["set_threshold_v1_thresholds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_v1_admin_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Identifier */
            identifier: string;
            /** Sender */
            sender: string;
            /**
             * Sent
             * Format: date-time
             */
            sent: string;
            /** Status */
            status: string;
            /** Msg Type */
            msg_type: string;
            /** Scope */
            scope: string;
            /** Category */
            category: string;
            /** Event */
            event: string;
            /** Urgency */
            urgency: string;
            /** Severity */
            severity: string;
            /** Certainty */
            certainty: string;
            /** Headline */
            headline: string;
            /** Description */
            description: string;
            /** Polygon */
            polygon: number[][];
        };
        /** AlertResponse */
        AlertResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            data: components["schemas"]["Alert"];
        };
        /** AlertsResponse */
        AlertsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["Alert"][];
            pagination: components["schemas"]["PaginatedResponse"];
        };
        /** Cell */
        Cell: {
            /** Cell Id */
            cell_id: string;
            /** Frame Id */
            frame_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Area Km2 */
            area_km2: number;
            /** Max Dbz */
            max_dbz: number;
            /** Max Vil */
            max_vil: number;
            /** Polygon H3 */
            polygon_h3: string[];
        };
        /** CellResponse */
        CellResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            data: components["schemas"]["Cell"];
        };
        /** CellsResponse */
        CellsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["Cell"][];
            pagination: components["schemas"]["PaginatedResponse"];
        };
        /** ETA */
        ETA: {
            /** Location Id */
            location_id: string;
            /** Hazard Type */
            hazard_type: string;
            /**
             * P10 Time
             * Format: date-time
             */
            p10_time: string;
            /**
             * P50 Time
             * Format: date-time
             */
            p50_time: string;
            /**
             * P90 Time
             * Format: date-time
             */
            p90_time: string;
            /** Probability Of Impact */
            probability_of_impact: number;
            /** State */
            state: string;
        };
        /** ETAResponse */
        ETAResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["ETA"][];
            pagination: components["schemas"]["PaginatedResponse"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardField */
        HazardField: {
            /** Hazard Type */
            hazard_type: string;
            /**
             * Valid Time
             * Format: date-time
             */
            valid_time: string;
            /** H3 Indices */
            h3_indices: string[];
            /** Severity */
            severity: string;
            /** Probability */
            probability: number;
        };
        /** HazardsResponse */
        HazardsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["HazardField"][];
            pagination: components["schemas"]["PaginatedResponse"];
        };
        /** ModelCard */
        ModelCard: {
            /** Model Id */
            model_id: string;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /**
             * Training Date
             * Format: date-time
             */
            training_date: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
        };
        /** ModelsResponse */
        ModelsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["ModelCard"][];
        };
        /** PaginatedResponse */
        PaginatedResponse: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Provenanced[Any] */
        Provenanced_Any_: {
            /** Source */
            source: string;
            /**
             * Valid Time
             * Format: date-time
             */
            valid_time: string;
            /**
             * Ingest Time
             * Format: date-time
             */
            ingest_time: string;
            /** Age Seconds */
            age_seconds: number;
            status: components["schemas"]["Status"];
            /**
             * Quality Flags
             * @default {}
             */
            quality_flags: {
                [key: string]: unknown;
            };
            /**
             * Is Observation
             * @default false
             */
            is_observation: boolean;
            /** Data */
            data?: unknown;
            /** Engine */
            engine?: string | null;
            /** Method */
            method?: string | null;
            skilful?: components["schemas"]["SkilfulFlag"] | null;
        };
        /** ReplayControlResponse */
        ReplayControlResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: string;
        };
        /** ReplayEventsResponse */
        ReplayEventsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: string[];
        };
        /** SingleETAResponse */
        SingleETAResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            data: components["schemas"]["ETA"];
        };
        /**
         * SkilfulFlag
         * @enum {string}
         */
        SkilfulFlag: "true" | "false" | "unknown";
        /** SourceHealth */
        SourceHealth: {
            /** Source Id */
            source_id: string;
            /**
             * Last Ingest
             * Format: date-time
             */
            last_ingest: string;
            /** Status */
            status: string;
            /** Lag Seconds */
            lag_seconds: number;
        };
        /** SourceHealthResponse */
        SourceHealthResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["SourceHealth"][];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "live" | "cached" | "stale" | "simulated" | "unavailable" | "needs_credentials";
        /** StatusResponse */
        StatusResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: string;
        };
        /** Threshold */
        Threshold: {
            /** Hazard Type */
            hazard_type: string;
            /** Metric */
            metric: string;
            /** Operator */
            operator: string;
            /** Value */
            value: number;
            /** Severity Level */
            severity_level: string;
        };
        /** ThresholdsResponse */
        ThresholdsResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["Threshold"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationResponse */
        VerificationResponse: {
            provenance: components["schemas"]["Provenanced_Any_"];
            /** Data */
            data: components["schemas"]["VerificationResult"][];
        };
        /** VerificationResult */
        VerificationResult: {
            /** Model Id */
            model_id: string;
            /**
             * Evaluation Time
             * Format: date-time
             */
            evaluation_time: string;
            /** Pod */
            pod: number;
            /** Far */
            far: number;
            /** Csi */
            csi: number;
            /** Hss */
            hss: number;
            /** Fss */
            fss: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_source_health_v1_health_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthResponse"];
                };
            };
        };
    };
    list_cells_v1_cells_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                /** @description Bounding box filter */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cell_v1_cells__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eta_v1_eta_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ETAResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_eta_v1_locations__id__eta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleETAResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hazards_v1_hazards__layer__get: {
        parameters: {
            query?: {
                lead?: number | null;
                bbox?: string | null;
            };
            header?: never;
            path: {
                layer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_v1_tiles__layer___z___x___y__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_v1_alerts_get: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Alert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_alert_v1_alerts__id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_alert_v1_alerts__id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_verification_v1_verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    list_replay_events_v1_replay_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayEventsResponse"];
                };
            };
        };
    };
    control_replay_v1_replay__event_id__control_get: {
        parameters: {
            query: {
                action: string;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thresholds_v1_thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
        };
    };
    set_threshold_v1_thresholds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Threshold"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_v1_admin_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
