import React, { useState } from 'react';

type Location = { id: string; name: string; hazards: string[]; etaMinutes: number | null };

// Locations will be loaded from API

export function AlertComposer({ onClose }: { onClose: () => void }) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [locations, setLocations] = useState<Location[]>([]);

  React.useEffect(() => {
    fetch('/v1/eta')
      .then(res => res.json())
      .then(data => {
        if (data.items) {
          setLocations(data.items.map((i: any) => ({
            id: i.cell_id || String(Math.random()),
            name: i.cell_id || 'Unknown',
            hazards: i.dominant_hazard ? [i.dominant_hazard] : [],
            etaMinutes: i.eta_minutes || null
          })));
        }
      })
      .catch(() => setLocations([]));
  }, []);

  const toggleSelection = (id: string) => {
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setSelectedIds(newSet);
  };

  const selectedLocs = locations.filter(l => selectedIds.has(l.id));
  const autoGeneratedText = selectedLocs.length > 0 
    ? `URGENT WEATHER ALERT:\n${selectedLocs.map(l => `- ${l.name}: ${l.hazards.join(', ')} expected in ${l.etaMinutes} mins.`).join('\n')}\nPlease take necessary precautions immediately.`
    : 'Select locations to auto-generate alert text.';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="w-[500px] rounded-xl border border-slate-700 bg-slate-900 shadow-2xl">
        <div className="border-b border-slate-800 p-4">
          <h2 className="text-lg font-bold text-slate-100">Compose Alert</h2>
        </div>
        
        <div className="p-4 space-y-4">
          <div>
            <h3 className="mb-2 text-sm font-semibold text-slate-400">Affected Locations</h3>
            <div className="space-y-2 rounded-md border border-slate-800 bg-slate-950 p-3">
              {locations.length === 0 && <div className="text-slate-500 text-xs">No locations found.</div>}
              {locations.map(loc => (
                <label key={loc.id} className="flex items-center gap-2 text-sm text-slate-200">
                  <input 
                    type="checkbox" 
                    checked={selectedIds.has(loc.id)} 
                    onChange={() => toggleSelection(loc.id)}
                    className="rounded border-slate-700 bg-slate-800 accent-cyan-500" 
                  />
                  <span>{loc.name}</span>
                </label>
              ))}
            </div>
          </div>

          <div>
            <h3 className="mb-2 text-sm font-semibold text-slate-400">Alert Message Preview</h3>
            <textarea 
              readOnly 
              className="h-32 w-full resize-none rounded-md border border-slate-800 bg-slate-950 p-3 text-sm text-red-400 focus:outline-none"
              value={autoGeneratedText}
            />
          </div>
        </div>

        <div className="flex items-center justify-end gap-3 border-t border-slate-800 p-4 bg-slate-900/50 rounded-b-xl">
          <button 
            onClick={onClose}
            className="rounded-md border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:bg-slate-800"
          >
            Cancel
          </button>
          <button 
            onClick={() => {
              alert('Alert Approved');
              onClose();
            }}
            disabled={selectedIds.size === 0}
            className="rounded-md bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Approve & Issue Alert
          </button>
        </div>
      </div>
    </div>
  );
}
