# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-10-03T06:18:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class Alert(BaseModel):
    identifier: str = Field(..., title='Identifier')
    sender: str = Field(..., title='Sender')
    sent: AwareDatetime = Field(..., title='Sent')
    status: str = Field(..., title='Status')
    msg_type: str = Field(..., title='Msg Type')
    scope: str = Field(..., title='Scope')
    category: str = Field(..., title='Category')
    event: str = Field(..., title='Event')
    urgency: str = Field(..., title='Urgency')
    severity: str = Field(..., title='Severity')
    certainty: str = Field(..., title='Certainty')
    headline: str = Field(..., title='Headline')
    description: str = Field(..., title='Description')
    polygon: list[list[float]] = Field(..., title='Polygon')


class Cell(BaseModel):
    cell_id: str = Field(..., title='Cell Id')
    frame_id: str = Field(..., title='Frame Id')
    lat: float = Field(..., title='Lat')
    lon: float = Field(..., title='Lon')
    area_km2: float = Field(..., title='Area Km2')
    max_dbz: float = Field(..., title='Max Dbz')
    max_vil: float = Field(..., title='Max Vil')
    polygon_h3: list[str] = Field(..., title='Polygon H3')


class ETA(BaseModel):
    location_id: str = Field(..., title='Location Id')
    hazard_type: str = Field(..., title='Hazard Type')
    p10_time: AwareDatetime = Field(..., title='P10 Time')
    p50_time: AwareDatetime = Field(..., title='P50 Time')
    p90_time: AwareDatetime = Field(..., title='P90 Time')
    probability_of_impact: float = Field(..., title='Probability Of Impact')
    state: str = Field(..., title='State')


class HazardField(BaseModel):
    hazard_type: str = Field(..., title='Hazard Type')
    valid_time: AwareDatetime = Field(..., title='Valid Time')
    h3_indices: list[str] = Field(..., title='H3 Indices')
    severity: str = Field(..., title='Severity')
    probability: float = Field(..., title='Probability')


class ModelCard(BaseModel):
    model_id: str = Field(..., title='Model Id')
    version: str = Field(..., title='Version')
    description: str = Field(..., title='Description')
    training_date: AwareDatetime = Field(..., title='Training Date')
    metrics: dict[str, float] = Field(..., title='Metrics')


class PaginatedResponse(BaseModel):
    total: int = Field(..., title='Total')
    page: int = Field(..., title='Page')
    size: int = Field(..., title='Size')


class SkilfulFlag(Enum):
    true = 'true'
    false = 'false'
    unknown = 'unknown'


class SourceHealth(BaseModel):
    source_id: str = Field(..., title='Source Id')
    last_ingest: AwareDatetime = Field(..., title='Last Ingest')
    status: str = Field(..., title='Status')
    lag_seconds: float = Field(..., title='Lag Seconds')


class Status(Enum):
    live = 'live'
    cached = 'cached'
    stale = 'stale'
    simulated = 'simulated'
    unavailable = 'unavailable'
    needs_credentials = 'needs_credentials'


class Threshold(BaseModel):
    hazard_type: str = Field(..., title='Hazard Type')
    metric: str = Field(..., title='Metric')
    operator: str = Field(..., title='Operator')
    value: float = Field(..., title='Value')
    severity_level: str = Field(..., title='Severity Level')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class VerificationResult(BaseModel):
    model_id: str = Field(..., title='Model Id')
    evaluation_time: AwareDatetime = Field(..., title='Evaluation Time')
    pod: float = Field(..., title='Pod')
    far: float = Field(..., title='Far')
    csi: float = Field(..., title='Csi')
    hss: float = Field(..., title='Hss')
    fss: float = Field(..., title='Fss')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class ProvenancedAny(BaseModel):
    source: str = Field(..., title='Source')
    valid_time: AwareDatetime = Field(..., title='Valid Time')
    ingest_time: AwareDatetime = Field(..., title='Ingest Time')
    age_seconds: float = Field(..., title='Age Seconds')
    status: Status
    quality_flags: dict[str, Any] | None = Field({}, title='Quality Flags')
    is_observation: bool | None = Field(False, title='Is Observation')
    data: Any | None = Field(None, title='Data')
    engine: str | None = Field(None, title='Engine')
    method: str | None = Field(None, title='Method')
    skilful: SkilfulFlag | None = None


class ReplayControlResponse(BaseModel):
    provenance: ProvenancedAny
    data: str = Field(..., title='Data')


class ReplayEventsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[str] = Field(..., title='Data')


class SingleETAResponse(BaseModel):
    provenance: ProvenancedAny
    data: ETA


class SourceHealthResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[SourceHealth] = Field(..., title='Data')


class StatusResponse(BaseModel):
    provenance: ProvenancedAny
    data: str = Field(..., title='Data')


class ThresholdsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[Threshold] = Field(..., title='Data')


class VerificationResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[VerificationResult] = Field(..., title='Data')


class AlertResponse(BaseModel):
    provenance: ProvenancedAny
    data: Alert


class AlertsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[Alert] = Field(..., title='Data')
    pagination: PaginatedResponse


class CellResponse(BaseModel):
    provenance: ProvenancedAny
    data: Cell


class CellsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[Cell] = Field(..., title='Data')
    pagination: PaginatedResponse


class ETAResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[ETA] = Field(..., title='Data')
    pagination: PaginatedResponse


class HazardsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[HazardField] = Field(..., title='Data')
    pagination: PaginatedResponse


class ModelsResponse(BaseModel):
    provenance: ProvenancedAny
    data: list[ModelCard] = Field(..., title='Data')
