/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SourceId = string;
export type ProductName = string;
export type ValidTime = string;
export type FilePath = string;
export type FrameId = string;
export type ValidTime1 = string;
export type ZarrUrl = string;
export type Variables = string[];
export type TileId = string | null;
export type CellId = string;
export type FrameId1 = string;
export type Lat = number;
export type Lon = number;
export type AreaKm2 = number;
export type MaxDbz = number;
export type MaxVil = number;
export type PolygonH3 = string[];
export type TrackId = string;
export type HistoryCellIds = string[];
export type SpeedMs = number;
export type DirectionDeg = number;
export type IsActive = boolean;
export type TrackId1 = string;
export type BaseTime = string;
export type LeadTimeMinutes = number;
export type PredictedLat = number;
export type PredictedLon = number;
export type PredictedPolygonH3 = string[];
export type IntensityTrend = string;
export type HazardType = string;
export type ValidTime2 = string;
export type H3Indices = string[];
export type Severity = string;
export type Probability = number;
export type Id = string;
export type Type = string;
export type Name = string;
export type H3Index = string;
export type Priority = number;
export type LocationId = string;
export type HazardType1 = string;
export type P10Time = string;
export type P50Time = string;
export type P90Time = string;
export type ProbabilityOfImpact = number;
export type State = string;
export type Identifier = string;
export type Sender = string;
export type Sent = string;
export type Status = string;
export type MsgType = string;
export type Scope = string;
export type Category = string;
export type Event = string;
export type Urgency = string;
export type Severity1 = string;
export type Certainty = string;
export type Headline = string;
export type Description = string;
export type Polygon = number[][];
export type EntryId = string;
export type Timestamp = string;
export type Action = string;
export type Actor = string;
export type PrevHash = string | null;
export type Hash = string;
export type HazardType2 = string;
export type Metric = string;
export type Operator = string;
export type Value = number;
export type SeverityLevel = string;
export type ModelId = string;
export type Version = string;
export type Description1 = string;
export type TrainingDate = string;
export type ModelId1 = string;
export type EvaluationTime = string;
export type Pod = number;
export type Far = number;
export type Csi = number;
export type Hss = number;
export type Fss = number;
export type SourceId1 = string;
export type LastIngest = string;
export type Status1 = string;
export type LagSeconds = number;

export interface VajraCoreSchemas {
  RawEvent?: RawEvent;
  FusedFrameRef?: FusedFrameRef;
  Cell?: Cell;
  CellTrack?: CellTrack;
  CellForecast?: CellForecast;
  HazardField?: HazardField;
  Location?: Location;
  ETA?: ETA;
  Alert?: Alert;
  AuditEntry?: AuditEntry;
  Threshold?: Threshold;
  ModelCard?: ModelCard;
  VerificationResult?: VerificationResult;
  SourceHealth?: SourceHealth;
}
export interface RawEvent {
  source_id: SourceId;
  product_name: ProductName;
  valid_time: ValidTime;
  file_path: FilePath;
  metadata?: Metadata;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface FusedFrameRef {
  frame_id: FrameId;
  valid_time: ValidTime1;
  zarr_url: ZarrUrl;
  variables: Variables;
  tile_id?: TileId;
}
export interface Cell {
  cell_id: CellId;
  frame_id: FrameId1;
  lat: Lat;
  lon: Lon;
  area_km2: AreaKm2;
  max_dbz: MaxDbz;
  max_vil: MaxVil;
  polygon_h3: PolygonH3;
}
export interface CellTrack {
  track_id: TrackId;
  history_cell_ids: HistoryCellIds;
  speed_ms: SpeedMs;
  direction_deg: DirectionDeg;
  is_active: IsActive;
}
export interface CellForecast {
  track_id: TrackId1;
  base_time: BaseTime;
  lead_time_minutes: LeadTimeMinutes;
  predicted_lat: PredictedLat;
  predicted_lon: PredictedLon;
  predicted_polygon_h3: PredictedPolygonH3;
  intensity_trend: IntensityTrend;
}
export interface HazardField {
  hazard_type: HazardType;
  valid_time: ValidTime2;
  h3_indices: H3Indices;
  severity: Severity;
  probability: Probability;
}
export interface Location {
  id: Id;
  type: Type;
  name: Name;
  h3_index: H3Index;
  priority?: Priority;
}
export interface ETA {
  location_id: LocationId;
  hazard_type: HazardType1;
  p10_time: P10Time;
  p50_time: P50Time;
  p90_time: P90Time;
  probability_of_impact: ProbabilityOfImpact;
  state: State;
}
export interface Alert {
  identifier: Identifier;
  sender: Sender;
  sent: Sent;
  status: Status;
  msg_type: MsgType;
  scope: Scope;
  category: Category;
  event: Event;
  urgency: Urgency;
  severity: Severity1;
  certainty: Certainty;
  headline: Headline;
  description: Description;
  polygon: Polygon;
}
export interface AuditEntry {
  entry_id: EntryId;
  timestamp: Timestamp;
  action: Action;
  actor: Actor;
  details: Details;
  prev_hash?: PrevHash;
  hash: Hash;
}
export interface Details {
  [k: string]: unknown;
}
export interface Threshold {
  hazard_type: HazardType2;
  metric: Metric;
  operator: Operator;
  value: Value;
  severity_level: SeverityLevel;
}
export interface ModelCard {
  model_id: ModelId;
  version: Version;
  description: Description1;
  training_date: TrainingDate;
  metrics: Metrics;
}
export interface Metrics {
  [k: string]: number;
}
export interface VerificationResult {
  model_id: ModelId1;
  evaluation_time: EvaluationTime;
  pod: Pod;
  far: Far;
  csi: Csi;
  hss: Hss;
  fss: Fss;
}
export interface SourceHealth {
  source_id: SourceId1;
  last_ingest: LastIngest;
  status: Status1;
  lag_seconds: LagSeconds;
}
